site:
  about:
    siteName: 'Built with Gradle'
    subtitle: 'Gradle refreshVersions, Kotlin, Android & more'
    siteDescription: 'Here we talk about building cool stuff with Gradle and Kotlin, Dependencies Management, Android and more'
    avatar: '/assets/media/logo.jpg'

theme:
  social:
    facebook: ''
    twitter: ''
    instagram: ''
    github: 'jmfayard/gradle-dependencies-plugins'
    other:
      - label: 'Dev.to'
        link: 'https://dev.to/jmfayard/'
        icon: 'fa fa-dev'    
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/jmfayard/'
        icon: 'fa fa-linkedin'
      - label: 'Kotlinlang slack'
        link: 'https://app.slack.com/client/T09229ZC6/CP5659EL9'
        icon: 'fa fa-slack-hash'
  menu:
    - type: "pages"
      atRoot: true
    #- type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'Contact'
      itemId: 'jmfayard'
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'
