permalink: ':category/:slug'
categories:
  - key: 'articles'
    title: 'Articles'
authors:
  - name: 'Author Two'
    avatar: 'assets/images/avatar.jpg'
    email: 'email@domain.tld'
postPages:
  author: 'jmfayard'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
